language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: VC4QPD50xxTbowNkUVK45wFlNOZu/9IwuEvl54NGZvZHPq+QnAZV3LZmeF5YWA1yupC5HBbDqkaRO5NmO2ABJF+eEV7Q7N+Ulp9orWDRq/gdCFasE3c8FGxqEb7Bec/s24RODRxffAQag5c7Bj+zD2mMuEpiE2rWLt2QSQNLCbjRGYBVzoY2AMePJ5ZF4xsPZWspb8WeyHMT/8O+jMF/WeKVSjVaddKBVfQryLlBGIHu85APadfjtc0mCQWpK86VoSOswma8mMLvL5n8N6U8nI0eP317pO+GNXl+fT4putsSkQZ8/a0AILQMWQy3cOgEToLv89mJavurVwmBq/N6xgC1stmVs+E8nVUfTlCDRvv7Os2FuOkXMZmRlnYq6UbqMO1PqxEpGlNoBRzyRRmXicV/JQeWD4ElfREaetly8vgDgkKNs6ymHfX8/UvpzNWc63yOpT2DvryeqVuSekGXffKNvPcCEqjwgWAY9fqIGJZsrQa/FY6ESn0qjmys1D1rBViwBfMRX/JgwJ3BN/V/e400b3sid/2qjOwk95tH39izOU+I4yFwXbyWuiN9gG+rUnSFOhuDxSgYw2D7K/7Wl8OtZe7f1fz6T0k267/MgahcRzTBJ+jhxvRRfhUKFSjV0geUSLhsWRzu2rK/T7XtB7hve1TGIwX6mC4vxjpRyB8=
  app: evening-peak-87515
